name: Deploy to GitHub Pages
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace API Token
        run: |
          sed -i 's/__API_TOKEN__/${{ secrets.API_TOKEN }}/g' gallery.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Deploys root files
